### ISSUE TITLE
Failed prop type: Invalid prop `carousel` of type `object` supplied to `CarouselControl`, expected a single ReactElement.

### ISSUE THREAD

**Issue by xhuang1024** [LZHD/teaset-pro#24]
这两天刚建的项目，teaset-pro的版本是0.8.5。

**Comment by LZHD** [comment]
![选区_011](https://user-images.githubusercontent.com/9976942/124360613-56b98480-dc5d-11eb-8e79-dbcbc60b9a0b.png)
参数类型错误，报错很清楚啊

**Comment by xhuang1024** [comment]
我是从其它项目拷贝过来的代码，之前是没有传这个参数的。我在API文档里也没有找到这个参数说明，不知道这个参数是要怎么用。

**Comment by LZHD** [comment]
这个参数其实是不用传的，`carousel` 是 `CarouselControl` 对应父组件 `Carousel` 的`实例`, 用来在子组件 `CarouselControl` 中控制父组件 `Carousel` 的行为。

![选区_013](https://user-images.githubusercontent.com/9976942/124373335-1ccf9900-dcc4-11eb-8233-dbee44d1f090.png)

**Comment by LZHD** [comment]
如果对 `React` 和 `React Native` 感兴趣的话可以尝试看看源代码的，我在原仓库 [teaset](https://github.com/rilyu/teaset) 的基础上重构和替换了部分代码和废弃的 `API`, 而且也做了代码的格式化，不是特别难懂的。

**Comment by xhuang1024** [comment]
好的，谢谢大佬。我是刚入门的新手，以后还有很多地方需要向大佬学习。上面那个carousel参数在代码中我没有传，即使用你demo里的例子也是会报上面的类型错误，但是功能貌似都是正常的，没影响使用。

**Comment by LZHD** [comment]
不是大佬，互相学习吧！

**Comment by LZHD** [comment]
@huangx1024  fix 0.8.6
